AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  domainName:
    Type: String
  restApiName:
    Type: String
  trustStoreUri:
    Type: String
  apiHostCert:
    Type: String
  s3Credential:
    Type: String
  rootEndpointUri:
    Type: String
  hostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  ssmResource:
    Type: String
  ssmPath:
    Type: String
  doorStreamPath:
    Type: String
  alarmTopic:
    Type: String

Resources:
  StunningDisco:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref restApiName
      DisableExecuteApiEndpoint: True
      BinaryMediaTypes:
        - "*/*" # Allow for images to be returned by lambda proxy
      EndpointConfiguration:
        Types:
          - REGIONAL

  StunningDiscoDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref domainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      MutualTlsAuthentication:
        TruststoreUri: !Ref trustStoreUri
      RegionalCertificateArn: !Ref apiHostCert
      SecurityPolicy: TLS_1_2

  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      RestApiId: !Ref StunningDisco
      DeploymentId: !Ref StunningDiscoDeployment
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: True
          ThrottlingBurstLimit: '10'
          ThrottlingRateLimit: '10.0'

  StunningDiscoDomainMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    DependsOn: ProdStage
    Properties:
      DomainName: !Ref StunningDiscoDomain
      RestApiId: !Ref StunningDisco
      Stage: !Ref ProdStage

  StunningDiscoDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - StunningDiscoRootEndpoint
      - StaticProxyResource
      - ApiProxyResource
      - StreamsDoorResource
      - StreamsMotionResource
      - UserIdentityResource
    Properties:
      RestApiId: !Ref StunningDisco

  StunningDiscoDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref 'hostedZoneId'
      Name: !Ref domainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt StunningDiscoDomain.RegionalHostedZoneId
        DNSName: !GetAtt StunningDiscoDomain.RegionalDomainName

  StunningDiscoRootEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !GetAtt StunningDisco.RootResourceId
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Root path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref rootEndpointUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  StreamsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: streams
      RestApiId: !Ref StunningDisco

  StreamsDoorResource:
    DependsOn: StreamsResource
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref StreamsResource
      PathPart: door
      RestApiId: !Ref StunningDisco

  StreamsMotionResource:
    DependsOn: StreamsResource
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref StreamsResource
      PathPart: motion
      RestApiId: !Ref StunningDisco

  StreamsMotionEndpoint:
    DependsOn:
      - ServeImageLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StreamsMotionResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "Serve motion asset by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: POST # needs to be POST
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${ServeMotionLambda.Arn}/invocations # ARN

  StreamsDoorInvokeEndpoint:
    DependsOn:
      - HttpRequestLambda
      - StreamsDoorResource
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StreamsDoorResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "Invoke door stream"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${RedirectLambda.Arn}/invocations # ARN

  ApiResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: api
      RestApiId: !Ref StunningDisco

  ApiProxyResource:
    DependsOn:
      - ApiResource
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref ApiResource
      PathPart: "{proxy+}"
      RestApiId: !Ref StunningDisco

  ApiProxyEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref ApiProxyResource
      HttpMethod: ANY
      AuthorizationType: NONE
      OperationName: "API proxy endpoint"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HttpRequestLambda.Arn}/invocations # ARN

  StaticResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: static
      RestApiId: !Ref StunningDisco

  StaticProxyResource:
    Type: AWS::ApiGateway::Resource
    DependsOn: StaticResource
    Properties:
      ParentId: !Ref StaticResource
      PathPart: "{proxy+}"
      RestApiId: !Ref StunningDisco

  StaticProxyEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StaticProxyResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "Static resource proxy endpoint"
      RequestParameters:
        method.request.path.proxy: true
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Sub arn:aws:apigateway:us-east-1:s3:path/${domainName}/{proxy}
        RequestParameters:
          integration.request.path.proxy: method.request.path.proxy
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty", "image/png": "Empty" }

  HttpRequestLambda:
    Type: 'AWS::Serverless::Function'
    DependsOn:
      - PythonSqsModuleLayer
      - PythonSsmModuleLayer
    Properties:
      FunctionName: 'http-request'
      Handler: http-request.lambda_handler
      Runtime: python3.8
      CodeUri: http-request.zip
      MemorySize: 128
      Timeout: 30
      Policies:
        - Statement:
            - Sid: SSMGetParamsByPath
              Effect: Allow
              Action:
                - ssm:GetParametersByPath
              Resource: !Ref ssmResource
        - Statement:
            - Sid: SQSpushRecord
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: 'arn:aws:sqs:us-east-1:476889715112:DatabaseMessageQueue'
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SSM_PATH: !Ref ssmPath
          TZ: America/New_York
      Layers:
        - !Ref PythonSqsModuleLayer
        - !Ref PythonSsmModuleLayer

  HttpRequestLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HttpRequestLambda}"
      RetentionInDays: 7

  HttpRequestLambdaAlarm: # Alarm if 1 bad data point (of >= 2 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref alarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '2'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref HttpRequestLambda

  ServeImageLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'serve-image'
      Handler: serve-image.lambda_handler
      Runtime: python3.8
      CodeUri: serve-image.zip
      MemorySize: 128
      Timeout: 30
      Role: !Ref s3Credential
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          BUCKET_NAME: !Ref domainName
          TZ: America/New_York

  ServeImageLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServeImageLambda}"
      RetentionInDays: 7

  ServeImageLambdaAlarm: # Alarm if 1 bad data point (of >= 2 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref alarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '2'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref ServeImageLambda

  PythonMysqlLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: pymysql_layer.zip
      LayerName: pymysql_layer

  PythonSqsModuleLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: sqs_module_layer.zip
      LayerName: sqs_module_layer

  PythonSsmModuleLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: ssm_module_layer.zip
      LayerName: ssm_module_layer

  ServeMotionLambda:
    Type: 'AWS::Serverless::Function'
    DependsOn:
      - PythonMysqlLayer
      - PythonSqsModuleLayer
      - PythonSsmModuleLayer
    Properties:
      FunctionName: 'serve-motion'
      Handler: serve-motion.lambda_handler
      Runtime: python3.8
      CodeUri: serve-motion.zip
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref PythonMysqlLayer
        - !Ref PythonSqsModuleLayer
        - !Ref PythonSsmModuleLayer
      Role: !Ref s3Credential
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SSM_PATH: !Ref ssmPath
          TZ: America/New_York

  ServeMotionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServeMotionLambda}"
      RetentionInDays: 7

  ServeMotionLambdaAlarm: # Alarm if 1 bad data point (of >= 2 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref alarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '2'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref ServeMotionLambda

  RedirectLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'redirect'
      Handler: redirect.lambda_handler
      Runtime: python3.8
      CodeUri: redirect.zip
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          REDIRECT_URL: !Ref doorStreamPath
          TZ: America/New_York

  RedirectLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${RedirectLambda}"
      RetentionInDays: 7

  RedirectLambdaAlarm: # Alarm if 1 bad data point (of >= 2 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref alarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '2'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref RedirectLambda

  UserIdentityLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'user-data'
      Handler: user-data.lambda_handler
      Runtime: python3.8
      CodeUri: user-data.zip
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole

  UserIdentityLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${UserIdentityLambda}"
      RetentionInDays: 7

  UserIdentityLambdaAlarm: # Alarm if 1 bad data point (of >= 2 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref alarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '2'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref UserIdentityLambda

  UserIdentityResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: user
      RestApiId: !Ref StunningDisco

  UserIdentityEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref UserIdentityResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "User identity endpoint"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${UserIdentityLambda.Arn}/invocations # ARN