AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  domainName:
    Type: String
  restApiName:
    Type: String
  trustStoreUri:
    Type: String
  apiHostCert:
    Type: String
  s3Credential:
    Type: String
  rootEndpointUri:
    Type: String
  hostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  lightsPageUri:
    Type: String
  doorPageUri:
    Type: String
  ssmResource:
    Type: String
  ssmPath:
    Type: String
  insidePageUri:
    Type: String
  outsidePageUri:
    Type: String
  faviconUri:
    Type: String
  doorStreamPath:
    Type: String
  streamsPageUri:
    Type: String
  stylesheetUri:
    Type: String
  streamsMotionPageUri:
    Type: String

Resources:
  StunningDisco:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref restApiName
      DisableExecuteApiEndpoint: True
      BinaryMediaTypes:
        - "*/*" # Allow for images to be returned by lambda proxy
      EndpointConfiguration:
        Types:
          - REGIONAL

  StunningDiscoDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref domainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      MutualTlsAuthentication:
        TruststoreUri: !Ref trustStoreUri
      RegionalCertificateArn: !Ref apiHostCert
      SecurityPolicy: TLS_1_2

  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      RestApiId: !Ref StunningDisco
      DeploymentId: !Ref StunningDiscoDeployment
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: True
          ThrottlingBurstLimit: '10'
          ThrottlingRateLimit: '10.0'

  StunningDiscoDomainMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    DependsOn: ProdStage
    Properties:
      DomainName: !Ref StunningDiscoDomain
      RestApiId: !Ref StunningDisco
      Stage: !Ref ProdStage

  StunningDiscoDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: [StunningDiscoRootEndpoint, LightsInvokeEndpoint]
    Properties:
      RestApiId: !Ref StunningDisco

  StunningDiscoDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref 'hostedZoneId'
      Name: !Ref domainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt StunningDiscoDomain.RegionalHostedZoneId
        DNSName: !GetAtt StunningDiscoDomain.RegionalDomainName

  StunningDiscoRootEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !GetAtt StunningDisco.RootResourceId
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Root path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref rootEndpointUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  StreamsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: streams
      RestApiId: !Ref StunningDisco

  StreamsPageEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StreamsResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Streams base path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref streamsPageUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  StreamsDoorResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref StreamsResource
      PathPart: door
      RestApiId: !Ref StunningDisco

  StreamsMotionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref StreamsResource
      PathPart: motion
      RestApiId: !Ref StunningDisco

  StreamsMotionPageEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StreamsMotionResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Streams motion base path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref streamsMotionPageUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  StreamsMotionBlobResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref StreamsMotionResource
      PathPart: blob
      RestApiId: !Ref StunningDisco

  StreamsMotionBlobEndpoint:
    DependsOn: ServeImageLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StreamsMotionBlobResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "Serve motion blob by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: POST # needs to be POST
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${ServeMotionLambda.Arn}/invocations # ARN

  StreamsDoorInvokeEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StreamsDoorResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "Invoke door stream"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${RedirectLambda.Arn}/invocations # ARN

  DoorResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: door
      RestApiId: !Ref StunningDisco

  DoorPageEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref DoorResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Door base path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref doorPageUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  DoorToggleResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref DoorResource
      PathPart: toggle
      RestApiId: !Ref StunningDisco

  DoorInvokeEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref DoorToggleResource
      HttpMethod: POST
      AuthorizationType: NONE
      OperationName: "Door toggle path by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HttpRequestLambda.Arn}/invocations # ARN

  LightsResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: lights
      RestApiId: !Ref StunningDisco

  LightsPageEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref LightsResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Lights base path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref lightsPageUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  InsideResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: inside
      RestApiId: !Ref StunningDisco

  InsidePageEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref InsideResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Inside base path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref insidePageUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  InsideArrangeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref InsideResource
      PathPart: arrange
      RestApiId: !Ref StunningDisco

  InsideInvokeEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref InsideArrangeResource
      HttpMethod: POST
      AuthorizationType: NONE
      OperationName: "Inside toggle path by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HttpRequestLambda.Arn}/invocations # ARN

  FaviconResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: favicon.ico
      RestApiId: !Ref StunningDisco

  FaviconEndpoint:
    DependsOn: ServeImageLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref FaviconResource
      HttpMethod: GET
      AuthorizationType: NONE
      OperationName: "Serve image by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: POST # needs to be POST
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${ServeImageLambda.Arn}/invocations # ARN

  StylesheetResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: style.css
      RestApiId: !Ref StunningDisco

  StylesheetEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref StylesheetResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Stylesheet path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref stylesheetUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/css": "Empty" }

  OutsideResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !GetAtt StunningDisco.RootResourceId
      PathPart: outside
      RestApiId: !Ref StunningDisco

  OutsidePageEndpoint:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref OutsideResource
      HttpMethod: "GET"
      AuthorizationType: NONE
      OperationName: "Outside base path"
      Integration:
        Type: "AWS"
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "GET"
        Uri: !Ref outsidePageUri
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200
          ResponseModels: { "text/html": "Empty" }

  OutsideArrangeResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref OutsideResource
      PathPart: arrange
      RestApiId: !Ref StunningDisco

  OutsideInvokeEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref OutsideArrangeResource
      HttpMethod: POST
      AuthorizationType: NONE
      OperationName: "Outside toggle path by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HttpRequestLambda.Arn}/invocations # ARN

  LightsToggleResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId: !Ref LightsResource
      PathPart: toggle
      RestApiId: !Ref StunningDisco

  LightsInvokeEndpoint:
    DependsOn: HttpRequestLambda
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref StunningDisco
      ResourceId: !Ref LightsToggleResource
      HttpMethod: POST
      AuthorizationType: NONE
      OperationName: "Lights toggle path by invoking lambda"
      Integration:
        Type: AWS_PROXY
        Credentials: !Ref s3Credential
        IntegrationHttpMethod: "POST"
        Uri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${HttpRequestLambda.Arn}/invocations # ARN

  HttpRequestLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'http-request'
      Handler: http-request.lambda_handler
      Runtime: python3.8
      CodeUri: http-request.zip
      MemorySize: 128
      Timeout: 30
      Policies:
        - Statement:
            - Sid: SSMGetParamsByPath
              Effect: Allow
              Action:
                - ssm:GetParametersByPath
              Resource: !Ref ssmResource
        - Statement:
            - Sid: SQSpushRecord
              Effect: Allow
              Action:
                - sqs:SendMessage
              Resource: 'arn:aws:sqs:us-east-1:476889715112:DatabaseMessageQueue'
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SSM_PATH: !Ref ssmPath
          TZ: America/New_York

  HttpRequestLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HttpRequestLambda}"
      RetentionInDays: 7

  ServeImageLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'serve-image'
      Handler: serve-image.lambda_handler
      Runtime: python3.8
      CodeUri: serve-image.zip
      MemorySize: 128
      Timeout: 30
      Role: !Ref s3Credential
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          BUCKET_NAME: !Ref domainName
          TZ: America/New_York

  ServeImageLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServeImageLambda}"
      RetentionInDays: 7

  PythonMysqlLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: pymysql_layer.zip
      LayerName: pymysql_layer

  ServeMotionLambda:
    Type: 'AWS::Serverless::Function'
    DependsOn: PythonMysqlLayer
    Properties:
      FunctionName: 'serve-motion'
      Handler: serve-motion.lambda_handler
      Runtime: python3.8
      CodeUri: serve-motion.zip
      MemorySize: 128
      Timeout: 30
      Layers:
        - !Ref PythonMysqlLayer
      Role: !Ref s3Credential
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SSM_PATH: !Ref ssmPath
          TZ: America/New_York

  ServeMotionLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServeMotionLambda}"
      RetentionInDays: 7

  RedirectLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'redirect'
      Handler: redirect.lambda_handler
      Runtime: python3.8
      CodeUri: redirect.zip
      Timeout: 5
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          REDIRECT_URL: !Ref doorStreamPath
          TZ: America/New_York

  RedirectLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${RedirectLambda}"
      RetentionInDays: 7

  StunningDiscoLambdaErrorsAlarm: # Alarm if 1 bad data point (of over 3 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - arn:aws:sns:us-east-1:476889715112:unhealthyHost
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '3'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName1
          Value: redirect
        - Name: FunctionName2
          Value: serve-image
        - Name: FunctionName3
          Value: http-request
        - Name: FunctionName4
          Value: serve-motion