variable "ssm_resources" {}
variable "sqs_resources" {}
variable "restApiName" {}
variable "apiHostCert" {}
variable "domainName" {}
variable "trustStoreUri" {}
variable "hostedZoneId" {}
variable "s3_resources" {}
variable "dynamo_table_name" {}
variable "rootEndpointUri" {}