AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  StunningDisco:
    Type: String
  alarmTopic:
    Type: String
  s3Credential:
    Type: String

Outputs:
  AuthorizerReference:
    Description: The ID of the VPC
    Value: !Ref Authorizer
    Export:
      Name: StunningDiscoAuthorizer

Resources:
  Authorizer:
    Type: AWS::ApiGateway::Authorizer
    DependsOn:
      - AuthorizerLambda
    Properties:
      AuthorizerCredentials: !Ref s3Credential
      AuthorizerResultTtlInSeconds: 0
      AuthorizerUri: !Sub arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/${AuthorizerLambda.Arn}/invocations
      Name: DefaultAuthorizer
      RestApiId: !Ref StunningDisco
      Type: REQUEST

  AuthorizerLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'authorizer'
      Handler: authorizer.lambda_handler
      Runtime: python3.8
      CodeUri: ../authorizer.zip
      MemorySize: 128
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole

  AuthorizerLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AuthorizerLambda}"
      RetentionInDays: 7

  AuthorizerLambdaLambdaAlarm: # Alarm if 1 bad data point (of >= 2 errors each) within 5 mins
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmActions:
        - !Ref alarmTopic
      ComparisonOperator: GreaterThanOrEqualToThreshold
      DatapointsToAlarm: 1 # this is the M in "M out of N data points to alarm"
      EvaluationPeriods: 5 # this is the N in "M out of N data points to alarm"
      MetricName: Errors
      Namespace: AWS/Lambda
      Period: 60 # seconds between data points
      Statistic: Sum
      Unit: Count
      Threshold: '2'
      TreatMissingData: notBreaching
      Dimensions:
        - Name: FunctionName
          Value: !Ref AuthorizerLambda