AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  TableName:
    Type: String
    Default: "StunningDiscoTable"

Outputs:
  StunningDiscoTableName:
    Value: !Ref TableName
    Export:
      Name: StunningDiscoTableName

Resources:
  StunningDiscoDdbTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "Timestamp"
          AttributeType: "S"
        -
          AttributeName: "Principal"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "Principal"
          KeyType: "HASH"
        -
          AttributeName: "Timestamp"
          KeyType: "RANGE"
      BillingMode: PROVISIONED
      ProvisionedThroughput:
        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref TableName
