AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'

Outputs:
  PythonMysqlLayerReference:
    Value: !Ref PythonMysqlLayer
    Export:
      Name: PythonMysqlLayerReference
  PythonSqsModuleLayerReference:
    Value: !Ref PythonSqsModuleLayer
    Export:
      Name: PythonSqsModuleLayerReference
  PythonSsmModuleLayerReference:
    Value: !Ref PythonSsmModuleLayer
    Export:
      Name: PythonSsmModuleLayerReference

Resources:
  PythonMysqlLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: pymysql_layer.zip
      LayerName: pymysql_layer

  PythonSqsModuleLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: sqs_module_layer.zip
      LayerName: sqs_module_layer

  PythonSsmModuleLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.8
      Content:
        S3Bucket: vizzyy-packaging
        S3Key: ssm_module_layer.zip
      LayerName: ssm_module_layer