AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  domainName:
    Type: String
  restApiName:
    Type: String
  trustStoreUri:
    Type: String
  apiHostCert:
    Type: String
  s3Credential:
    Type: String
  rootEndpointUri:
    Type: String
  hostedZoneId:
    Type: AWS::Route53::HostedZone::Id
  ssmResource:
    Type: String
  ssmPath:
    Type: String
  doorStreamPath:
    Type: String
  alarmTopic:
    Type: String
  sqsQueue:
    Type: String

Resources:
  StunningDisco:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Ref restApiName
      DisableExecuteApiEndpoint: True
      BinaryMediaTypes:
        - "*/*" # Allow for images to be returned by lambda proxy
      EndpointConfiguration:
        Types:
          - REGIONAL

  StunningDiscoDomain:
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: !Ref domainName
      EndpointConfiguration:
        Types:
          - REGIONAL
      MutualTlsAuthentication:
        TruststoreUri: !Ref trustStoreUri
      RegionalCertificateArn: !Ref apiHostCert
      SecurityPolicy: TLS_1_2

  ProdStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: Prod
      RestApiId: !Ref StunningDisco
      DeploymentId: !Ref StunningDiscoDeployment
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
          LoggingLevel: INFO
          DataTraceEnabled: True
          ThrottlingBurstLimit: '10'
          ThrottlingRateLimit: '10.0'

  StunningDiscoDomainMapping:
    Type: 'AWS::ApiGateway::BasePathMapping'
    DependsOn: ProdStage
    Properties:
      DomainName: !Ref StunningDiscoDomain
      RestApiId: !Ref StunningDisco
      Stage: !Ref ProdStage

  StunningDiscoDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - StreamsStack
      - DdbStack
      - ApiProxyStack
      - StaticProxyStack
      - AuthorizerProxyStack
      - PythonLayersStack
    Properties:
      RestApiId: !Ref StunningDisco

  StunningDiscoDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref 'hostedZoneId'
      Name: !Ref domainName
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt StunningDiscoDomain.RegionalHostedZoneId
        DNSName: !GetAtt StunningDiscoDomain.RegionalDomainName

  DdbStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: ddb_template.yml

  StreamsStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - AuthorizerProxyStack
      - PythonLayersStack
    Properties:
      Location: streams_template.yml
      Parameters:
        StunningDisco: !Ref StunningDisco
        s3Credential: !Ref s3Credential
        alarmTopic: !Ref alarmTopic
        StunningDiscoRootResource: !GetAtt StunningDisco.RootResourceId
        ssmPath: !Ref ssmPath
        doorStreamPath: !Ref doorStreamPath

  ApiProxyStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - AuthorizerProxyStack
      - PythonLayersStack
    Properties:
      Location: api_proxy_template.yml
      Parameters:
        StunningDisco: !Ref StunningDisco
        s3Credential: !Ref s3Credential
        alarmTopic: !Ref alarmTopic
        StunningDiscoRootResource: !GetAtt StunningDisco.RootResourceId
        ssmPath: !Ref ssmPath
        sqsQueue: !Ref sqsQueue
        ssmResource: !Ref ssmResource

  StaticProxyStack:
    Type: AWS::Serverless::Application
    DependsOn:
      - AuthorizerProxyStack
    Properties:
      Location: static_proxy_template.yml
      Parameters:
        StunningDisco: !Ref StunningDisco
        s3Credential: !Ref s3Credential
        StunningDiscoRootResource: !GetAtt StunningDisco.RootResourceId
        domainName: !Ref domainName
        rootEndpointUri: !Ref rootEndpointUri

  AuthorizerProxyStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: authorizer_template.yml
      Parameters:
        StunningDisco: !Ref StunningDisco
        alarmTopic: !Ref alarmTopic
        s3Credential: !Ref s3Credential

  PythonLayersStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: python_layers_template.yml
